### ISSUE TITLE
Tumbleweed 版本，依赖错误

### ISSUE THREAD

**Issue by yswtrue** [openSUSE-zh/wps-office-installer#3]
```
#### YaST2 conflicts list - generated 2019-11-01 14:00:55 ####

没有什么能提供 libhogweed4，而它为 wps-office-11.1.0.8392-1.12.i586 所需

    [ ] 通过忽略一些依赖关系来断开 wps-office-11.1.0.8392-1.12.i586

    [ ] 不安装 wps-office-11.1.0.8392-1.12.i586




#### YaST2 conflicts list END ###

```

**Comment by marguerite** [comment]
@yswtrue

安装最新版本。我去除了所有硬编码的运行依赖。装上后使用 `wps-office-installer -r  -d=/usr/share/wps-office` 获取依赖后使用 zypper 安装。

install the latest trunk in which all the runtime dependencies have been removed. then run `wps-office-installer -r -d=/usr/share/wps-office` to get the runtime dependencies used by `your running system`, that is, the output (package names) will differ for Tumbleweed and Leap. then use zypper to install them.
